### ISSUE TITLE
Erro nos textos de requisitos - Cadastro

### ISSUE THREAD

**Issue by davidtmasin** [jhonatasmatos/bugbank#42]
### Na seção de Cadastro, temos os seguintes textos que estão em desacordo:

1. Tentativa de cadastro sem preencher nome deve visualizar a mensagem **"Nome precisa ser vazio"**

2. **Deixar ativo** a opção "Criar conta com saldo" deve criar conta com **saldo de R$ 0,00**

Na execução dos meus cenários de teste, a mensagem apresentada ao cadastrar uma conta sem informar o nome foi a seguinte: "Nome não pode ser vazio". Também foi verificado que quando a opção **Criar conta com saldo** for ativada, a conta cadastrada terá sempre o valor de R$1000,00 e caso esta opção não venha a estar desativada, a nova conta terá um saldo de R$ 0,00.

<img src="https://github.com/davidtmasin/tests-bugbank/blob/main/RobotFramework/Errors/Evid%C3%AAncia%2001.png?raw=true">

**Comment by jhonatasmatos** [comment]
@davidtmasin muito obrigado por apontar esses erros, já estou analisando e vou corrigi-los e soltar uma nova versão, valeu !!!

**Comment by jhonatasmatos** [comment]
Correção feita no PR #46 e aplicada no release **1.0.2**
