### ISSUE TITLE
[Bug] - Login

### ISSUE THREAD

**Issue by davidtmasin** [jhonatasmatos/bugbank#43]
### Após efetuado o cadastro de uma nova conta. O processo de login ocorre normalmente, porém, foi observado um comportamento estranho:

- Ao tentar efetuar o login em outros dispositivos (Notebook Dell Inspiron 14 - Win10x64 e Smartphone Samsung A01 - Android 10), surge em tela a mensagem "**Usuário ou senha inválido. Tente novamente ou verifique suas informações**".

- Consigo efetuar o login na máquina (Notebook Lenovo - Win10x64) onde efetuei o cadastro, porém, quando tento executar o teste através da automatização do RobotFramework, a mesma mensagem "**Usuário ou senha inválido. Tente novamente ou verifique suas informações**" é apresentada.

### Realizei dois cadastros na plataforma e a situação ocorreu nos dois usuários, segue as credenciais para posterior análise:
**jailson@teste.com.br** / **teste1**
**paulo@teste.com.br** / **teste2**

<img src="https://github.com/davidtmasin/tests-bugbank/blob/main/RobotFramework/Errors/Evid%C3%AAncia%2002.png?raw=true">

Vídeo: https://github.com/davidtmasin/tests-bugbank/blob/main/RobotFramework/Errors/Evid%C3%AAncia%2002.mp4

**Comment by jhonatasmatos** [comment]
@davidtmasin infelizmente (ou felizmente), nós não contamos com um banco de dados/backend dessa aplicação, ela ainda funciona apenas na sessão atual ou seja, os dados que você cadastrou só funcionam na sua máquina, cada máquina ou dispositivos mobile, devem ter suas próprias contas.

Vou deixar como uma melhoria futura, desenvolver o backend da aplicação e ai sim, poderemos utilizar o mesmo usuário em diversos dispositivos 😄

**Comment by jhonatasmatos** [comment]
@davidtmasin foi adicionado no PR #48 e está na ultima versão **1.0.2** um warning onde diz que a aplicação tem uma base dados local, sendo assim não é possível criar contas em um computador e utilizar em outro.

Muito obrigado por fornecer todos os detalhes 😄
