### ISSUE TITLE
[Bug] - Login

### ISSUE THREAD

**Issue by Thairam** [jhonatasmatos/bugbank#44]
### Informações do host:
- SO: Windows 10x64
- Versão do Node: v14.17.1
- Versão do NPM: 6.14.13
- Versão do Yarn: 1.22.10
- Navegador: Chrome
- Versão do Navegador: 99.0.4844.84 (Versão oficial) 64 bits

### Falha

![bug bugbank](https://user-images.githubusercontent.com/32168179/161342001-af79f7e6-7e3b-42fd-92fe-5c22438c6488.png)

#### Inseri um `console.log()` para tentar entender o que ocorreu, o valor de `user` foi  a string `1cb04cf3f9f85daf8eead8f5409d5a31` e por esse motivo o `JSON.parse()` falhou.

![image](https://user-images.githubusercontent.com/32168179/161342419-276d7f9d-75b3-42fa-a9e7-f9fa32561b8f.png)

### Mais observações

O método `allStorage()` retorna um array, e em sua primeira posição, temos a string mencionada acima `1cb04cf3f9f85daf8eead8f5409d5a31`. Realizando um `JSON.stringify(users)` e obtive o seguinte resultado:

```
[
  "1cb04cf3f9f85daf8eead8f5409d5a31",
  "{\"userAgent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36\",\"version\":\"1.4.1\",\"focusAreaImgTabindex\":false,\"focusAreaTabindex\":false,\"focusAreaWithoutHref\":false,\"focusAudioWithoutControls\":false,\"focusBrokenImageMap\":true,\"focusChildrenOfFocusableFlexbox\":false,\"focusFieldsetDisabled\":false,\"focusFieldset\":false,\"focusFlexboxContainer\":false,\"focusFormDisabled\":true,\"focusImgIsmap\":false,\"focusImgUsemapTabindex\":true,\"focusInHiddenIframe\":true,\"focusInvalidTabindex\":false,\"focusLabelTabindex\":true,\"focusObjectSvg\":true,\"focusObjectSvgHidden\":false,\"focusRedirectImgUsemap\":false,\"focusRedirectLegend\":\"\",\"focusScrollBody\":false,\"focusScrollContainerWithoutOverflow\":false,\"focusScrollContainer\":false,\"focusSummary\":true,\"focusSvgFocusableAttribute\":false,\"focusSvgTabindexAttribute\":true,\"focusSvgNegativeTabindexAttribute\":true,\"focusSvgUseTabindex\":true,\"focusSvgForeignobjectTabindex\":true,\"focusSvg\":false,\"focusTabindexTrailingCharacters\":true,\"focusTable\":false,\"focusVideoWithoutControls\":false,\"cssShadowPiercingDeepCombinator\":\"\",\"focusInZeroDimensionObject\":true,\"focusObjectSwf\":true,\"focusSvgInIframe\":false,\"tabsequenceAreaAtImgPosition\":false,\"time\":\"2022-04-01T20:58:23.448Z\"}",
  "{\"name\":\"Thairam\",\"email\":\"thairam@gmail.com\",\"password\":\"senha\",\"accountNumber\":\"639-8\",\"balance\":1000,\"logged\":false}",
  "[{\"id\":\"0b90953d-5132-4ab3-b802-844562295b43\",\"date\":\"01/04/2022\",\"type\":\"Abertura de conta\",\"transferValue\":1000,\"description\":\"Saldo adicionado ao abrir conta\"}]",
  "{\"economiaSelecionada\":\"{\\\"idPerfil\\\":0,\\\"tipoConta\\\":\\\"\\\",\\\"idCondominio\\\":0,\\\"idLocacao\\\":0,\\\"endereco\\\":\\\"\\\",\\\"codigoCliente\\\":\\\"\\\",\\\"chaveAcesso\\\":\\\"\\\",\\\"chavePesquisaV1\\\":\\\"\\\",\\\"prefixoUrlV1\\\":\\\"\\\",\\\"idEconomia\\\":0,\\\"idPessoa\\\":0,\\\"codigoBanco\\\":\\\"\\\",\\\"nomeBanco\\\":\\\"\\\",\\\"codigoAgencia\\\":\\\"\\\",\\\"contaCorrente\\\":\\\"\\\",\\\"exibirSpinner\\\":true,\\\"possuiPerfilSelecionado\\\":false,\\\"nomePessoa\\\":\\\"\\\",\\\"administrador\\\":false}\",\"_persist\":\"{\\\"version\\\":-1,\\\"rehydrated\\\":true}\"}",
  "{\"_persist\":\"{\\\"version\\\":-1,\\\"rehydrated\\\":true}\"}"
]
```

Consegui identificar o problema, mas n sei qual o motivo da sua ocorrência.

**Comment by jhonatasmatos** [comment]
@Thairam obrigado pelo report, qual navegador você está utilizando ?
Estou tentando reproduzir o erro e não estou conseguindo 😪

**Comment by Thairam** [comment]
@jhonatasmatos estou utilizando o Chrome: Versão 99.0.4844.84 (Versão oficial) 64 bits

**Comment by Thairam** [comment]
@jhonatasmatos limpando manualmente o cache do local storage e refazendo o processo, funcionou. Consegui realizar login.

**Comment by jhonatasmatos** [comment]
@Thairam  estou fechando por enquanto, acredito que foi algum problema com o local storage, estamos implementando melhorias, caso aconteça novamente, abra uma nova issue para que possamos analisar melhor.

Muito obrigado por todas as informações!!!
