### ISSUE TITLE
Erro de login

### ISSUE THREAD

**Issue by santosvini** [jhonatasmatos/bugbank#56]
Opa Jhonatas, beleza!

Eu fiz teste de forma manual para validar o acesso a aplicação, segundo conforme as regras apontam, porém ao tentar fazer login, não retorna erro ou alguma mensagem, segue o print abaixo, eu verifiquei as issues fechadas, mas acredito que o bug tenha retornado!

Segue

![image](https://user-images.githubusercontent.com/46813491/228412383-e165d7ac-d37d-42c1-93d6-1f307171b23d.png)

Além do disparo de erros ao clicar em Acessar

![image](https://user-images.githubusercontent.com/46813491/228413054-92b0cd5a-9883-4082-9824-dad96efa10e9.png)

Abs

**Comment by PauloGoncalvesBH** [comment]
É feito alguma request ao clicar em Acessar?

**Comment by santosvini** [comment]
> É feito alguma request ao clicar em Acessar?

Opa Paulo, blz, prazer mano, segue 

![image](https://user-images.githubusercontent.com/46813491/228610021-977c30c1-fa92-4070-a805-bd9e37b75470.png)

**Comment by jhonatasmatos** [comment]
@PauloGoncalvesBH o bugbank nao tem APIs ainda, é tudo feito dentro do localStorage.

@santosvini acredito que a aplicaçao esta se perdendo na hora de fazer o parse do json com as suas informaçoes porque ele tem aquele loglevel INFO que nao deveria estar ali. Estou trabalhando em melhorias de flow e até mesmo pensando em implementar um backend para melhorar fluxos como o de login por exemplo.

Enquanto isso como workaround se voce puder apagar aquela primeira linha ali "loglevel": "INFO", acredito que ira funcionar.

**Comment by santosvini** [comment]
@jhonatasmatos foi consegui me logar apagando essa chave que você mencionou, um adendo é que ontem eu fiz isso também e não logava, pedi para um colega logar e ele conseguiu, enfim deu certo vou voltar a brincar

Obrigado

**Comment by jhonatasmatos** [comment]
valeu @santosvini  bons estudos, espero conseguir lançar a nova versao em breve, assim nao teremos mais imprevistos :D
